version: '3.4'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test

  bot:
    image: redis:alpine
    environment:
      ghcr.io/bots-house/docker-telegram-bot-api:latest