version: "3"
services:
  telegram-bot:
    image: golang:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=6732348036:AAEe16L4I5iMOrV3bLVY1f2cKTDMyytTe9c
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=telegram
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# Создаем именованный том для данных PostgreSQL
volumes:
  pgdata:

# Создаем сеть для взаимодействия контейнеров
networks:
  default:
    driver: bridge
