version: '3'
services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=6732348036:AAEe16L4I5iMOrV3bLVY1f2cKTDMyytTe9c
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root1
      - DB_NAME=users
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1
      - POSTGRES_DB=users
    volumes:
      - postgres_data:/var/lib/postgresql/data/