version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  bot:
    build: .
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: ${TELEGRAM_TOKEN}
      HOST: db
      PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      USER: ${POSTGRES_USER}
      DBNAME: ${POSTGRES_DB}
      SSLMODE: disable
    depends_on:
      - db