version: '3'
services:
  bot:
    build: .
    ports:
      - "443"
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      HOST: db
      SSLMODE: disable
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"