version: "3.9"
services:
  # Контейнер с телеграм-ботом
  mybot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - LANGUAGE=en
    restart: unless-stopped

  # Контейнер с PostgreSQL
  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_DB=telegram
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

# Создаем именованный том для данных PostgreSQL
volumes:
  pgdata:

# Создаем сеть для взаимодействия контейнеров
networks:
  default:
    driver: bridge
