version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_TOKEN: your_telegram_bot_token
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5432:5432"