version: '3'

services:
  bot:
    image: alpine:latest
    environment:
      TOKEN: 6732348036:AAEe16L4I5iMOrV3bLVY1f2cKTDMyytTe9c
  db:
    image: postgres
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on" 
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable