version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  bot:
    build: .
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TELEGRAM_TOKEN: 6732348036:AAEe16L4I5iMOrV3bLVY1f2cKTDMyytTe9c
      DBNAME: postgres
      USER: postgres
      HOST: db
      PORT: 5432
      SSLMODE: disable
      PASSWORD: password