version: '3'
services:
  db:
    image: postgres
    environment:
      
  bot:
    build: .
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: ${TELEGRAM_TOKEN}
      HOST: db
      PORT: 5432
      USER: ${POSTGRES_USER}
      
      DBNAME: ${POSTGRES_DB}
      SSLMODE: disable