version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      USER: ${POSTGRES_USER}
      DBNAME: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres
  bot:
    build: .
    depends_on:
      - db
    command: sh -c 'sleep 35'
    restart: on-failure
    volumes:
      - pgdata
    networks:
      - postgres
    env_file:
      - .env
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: ${TELEGRAM_TOKEN}
      HOST: db
      PORT: 5432
      SSLMODE: disable    