version: '3'
services:
  db:
    image: postgres
    environment:
      -  POSTGRES_PASSWORD=test
      -  USER: ${POSTGRES_USER}
      -  DBNAME: ${POSTGRES_DB}
  bot:
    build: .
    environment:
      -  POSTGRES_PASSWORD=test
      -  CREATE_TABLE="yes"
      -  DB_SWITCH="on"
      -  TELEGRAM_TOKEN=6732348036:AAEe16L4I5iMOrV3bLVY1f2cKTDMyytTe9c
      -  HOST: db
      -  PORT: 5432
      -  USER: ${POSTGRES_USER}
      -  DBNAME: ${POSTGRES_DB}
      -  SSLMODE: disable
    depends_on:
      - db